var L_EN = {
	admin : "Admin",
	addArticle : "Add article",
	removeArticle : "Remove Article",
	signout : "Sign out",
	blogSetup : "Blog setup",
	blogTitle : "Blog Title",
	title : "Title",
	yourName : "Your name",
	fullname : "Fullname",
	adminUsername : "Admin username",
	username : "Username",
	adminPassword : "Admin password",
	password : "Password",
	setup : "Setup",
	subtitle : "subtitle",
	body : "Article body",
	publish : "Publish",
	unpublish : "Unpublish",
	areYouSure : "Are you sure?",
	fullWeekDays : ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
	fullMonths : ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
	monthDay : "{{weekday}}, {{month}} {{day}}",
	fullDate : "{{weekday}}, {{month}} {{day}}, {{year}}",
	photoVideo : "Photo/Vídeo",
	photo : "Photo",
	add : "Add"
};
