var L_ES = {
	admin : "Admin",
	newArticle : "Nuevo artículo",
	removeArticle : "Eliminar Artículo",
	signout : "Cerrar sesión",
	blogSetup : "Configuración del blog",
	blogTitle : "Título del blog",
	title : "Título",
	yourName : "Tu Nombre",
	fullname : "Nombre completo",
	adminUsername : "Nombre de usuario",
	username : "Usuario",
	adminPassword : "Clave de administración",
	password : "Clave",
	setup : "Configurar",
	subtitle : "Subtítulo",
	body : "Cuerpo del artículo",
	publish : "Publicar",
	unpublish : "Dejar de publicar",
	areYouSure : "¿Estás seguro?",
	fullWeekDays : ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"],
	fullMonths : ["Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"],
	monthDay : "{{weekday}}, {{day}} de {{month}}",
	fullDate : "{{weekday}}, {{day}} de {{month}} de {{year}}",
};
